function [pwmlo, pwmhi, SurfaceLimits]=Cal_T2_Limits();
%function [pwmlo, pwmhi, SurfaceLimits]=Cal_T2_Limits();
%
%Autogenerated from UplinkSignalList spreadsheet on 17-Aug-2009 10:52:06
%$Id: Cal_T2_Limits.m 1928 2009-08-17 14:53:29Z murch $

%----------------------------------------------
% Limits on PWM signals, usec
%----------------------------------------------
pwmlo.AILLC=1200;    	pwmhi.AILLC=1850;    	% Left Aileron 
pwmlo.AILRC=1200;    	pwmhi.AILRC=1880;    	% Right Aileron 
pwmlo.SPLLIBC=1236;    	pwmhi.SPLLIBC=1785;    	% Left Inboard Spoiler 
pwmlo.SPLLOBC=1269;    	pwmhi.SPLLOBC=2105;    	% Left Outboard Spoiler 
pwmlo.SPLRIBC=1236;    	pwmhi.SPLRIBC=1785;    	% Right Inboard Spoiler 
pwmlo.SPLROBC=1248;    	pwmhi.SPLROBC=2105;    	% Right Outboard Spoiler 
pwmlo.ELLOBC=1100;    	pwmhi.ELLOBC=1900;    	% Left Outboard Elevator 
pwmlo.ELLIBC=1175;    	pwmhi.ELLIBC=1855;    	% Left Inboard Elevator 
pwmlo.ELROBC=1100;    	pwmhi.ELROBC=1900;    	% Right Outboard Elevator 
pwmlo.ELRIBC=1175;    	pwmhi.ELRIBC=1855;    	% Right Inboard Elevator 
pwmlo.RUDUPC=1075;    	pwmhi.RUDUPC=1865;    	% Upper Rudder 
pwmlo.RUDLOC=1075;    	pwmhi.RUDLOC=1865;    	% Lower Rudder 
pwmlo.THROTLC=1339;    	pwmhi.THROTLC=1900;    	% Left Throttle 
pwmlo.THROTRC=1339;    	pwmhi.THROTRC=1900;    	% Right Throttle 
pwmlo.GEARC=1111;    	pwmhi.GEARC=1900;    	% Gear Deploy / Retract 
pwmlo.LINK0=0;    	pwmhi.LINK0=4000;    	% Link Monitor Port 0 
pwmlo.FLAPLIC=1173;    	pwmhi.FLAPLIC=1910;    	% Left Inboard Flap 
pwmlo.FLAPLOC=1000;    	pwmhi.FLAPLOC=1910;    	% Left Outboard Flap 
pwmlo.FLAPRIC=1185;    	pwmhi.FLAPRIC=1910;    	% Right Inboard Flap 
pwmlo.FLAPROC=991;    	pwmhi.FLAPROC=1910;    	% Right Outboard Flap 
pwmlo.BRAKEC=1121;    	pwmhi.BRAKEC=1909;    	% Brake Command 
pwmlo.STEERC=1000;    	pwmhi.STEERC=2000;    	% Steer Command 
pwmlo.ENGML=1000;    	pwmhi.ENGML=2000;    	% Left Engine Mode 
pwmlo.ENGMR=1000;    	pwmhi.ENGMR=2000;    	% Right Engine Mode 
pwmlo.PWM24=1000;    	pwmhi.PWM24=2000;    	% Reserved 
pwmlo.PWM25=1000;    	pwmhi.PWM25=2000;    	% Reserved 
pwmlo.PWM26=1000;    	pwmhi.PWM26=2000;    	% Reserved 
pwmlo.PWM27=1000;    	pwmhi.PWM27=2000;    	% Reserved 
pwmlo.PWM28=1000;    	pwmhi.PWM28=2000;    	% Reserved 
pwmlo.PWM29=1000;    	pwmhi.PWM29=2000;    	% Reserved 
pwmlo.PWM30=1000;    	pwmhi.PWM30=2000;    	% Reserved 
pwmlo.LINK1=0;    	pwmhi.LINK1=4000;    	% Link Monitor Port 1 


%----------------------------------------------------
% Limits on Surface Commands, deg, percent, boolean
%------------------------------------------------------
SurfaceLimits.AILLC 	= [-30.00; 30.00];   	% Left Aileron 
SurfaceLimits.AILRC 	= [-30.00; 30.00];   	% Right Aileron 
SurfaceLimits.SPLLIBC 	= [ 0.00; 15.00];   	% Left Inboard Spoiler 
SurfaceLimits.SPLLOBC 	= [ 0.00; 45.00];   	% Left Outboard Spoiler 
SurfaceLimits.SPLRIBC 	= [ 0.00; 15.00];   	% Right Inboard Spoiler 
SurfaceLimits.SPLROBC 	= [ 0.00; 45.00];   	% Right Outboard Spoiler 
SurfaceLimits.ELLOBC 	= [-30.00; 20.00];   	% Left Outboard Elevator 
SurfaceLimits.ELLIBC 	= [-30.00; 20.00];   	% Left Inboard Elevator 
SurfaceLimits.ELROBC 	= [-30.00; 20.00];   	% Right Outboard Elevator 
SurfaceLimits.ELRIBC 	= [-30.00; 20.00];   	% Right Inboard Elevator 
SurfaceLimits.RUDUPC 	= [-30.00; 30.00];   	% Upper Rudder 
SurfaceLimits.RUDLOC 	= [-30.00; 30.00];   	% Lower Rudder 
SurfaceLimits.THROTLC 	= [ 0.00; 100.00];   	% Left Throttle 
SurfaceLimits.THROTRC 	= [ 0.00; 100.00];   	% Right Throttle 
SurfaceLimits.GEARC 	= [ 0.00;  1.00];   	% Gear Deploy / Retract 
SurfaceLimits.LINK0 	= [ 0.00;  1.00];   	% Link Monitor Port 0 
SurfaceLimits.FLAPLIC 	= [ 0.00; 45.00];   	% Left Inboard Flap 
SurfaceLimits.FLAPLOC 	= [ 0.00; 45.00];   	% Left Outboard Flap 
SurfaceLimits.FLAPRIC 	= [ 0.00; 45.00];   	% Right Inboard Flap 
SurfaceLimits.FLAPROC 	= [ 0.00; 45.00];   	% Right Outboard Flap 
SurfaceLimits.BRAKEC 	= [ 0.00; 100.00];   	% Brake Command 
SurfaceLimits.STEERC 	= [-30.00; 30.00];   	% Steer Command 
SurfaceLimits=rmfield(SurfaceLimits,'LINK0');
CmdOrder={'THROTLC','THROTRC',...
    'ELLOBC','ELLIBC','ELROBC','ELRIBC',...
    'AILLC',...
    'SPLLOBC','SPLLIBC','SPLRIBC','SPLROBC',...
    'AILRC',...
    'RUDUPC','RUDLOC',...
    'FLAPLOC','FLAPLIC','FLAPROC','FLAPRIC',...
    'GEARC','STEERC','BRAKEC'};
SurfaceLimits=orderfields(SurfaceLimits,CmdOrder);
