
if (ispc),
mex -v SimulinkToXPlane.cpp ./networking/PCSBSocketUDP.win.cpp ...
                         -L../obj -lwsock32 ...
                         -I./networking -I./usr/include -I./ ...
                         -outdir ../bin/mfiles/

mex -v MatlabToXPlane.cpp  ./networking/PCSBSocketUDP.win.cpp ...
                         -L../obj -lwsock32 ...
                         -I./networking -I./usr/include -I./ ...
                         -outdir ../bin/mfiles/

elseif (isunix),
mex -v SimulinkToXPlane.cpp ./networking/PCSBSocketUDP.lin.cpp ...
                          -I./networking -I./usr/include -I./ ...
                          -outdir ../bin/mfiles/   

mex -v MatlabToXPlane.cpp  ./networking/PCSBSocketUDP.lin.cpp ...
                          -I./networking -I./usr/include -I./ ...
                          -outdir ../bin/mfiles/   
elseif (ismac),
mex -v SimulinkToXPlane.cpp ./networking/PCSBSocketUDP.mac.cpp ...
                         -I./networking -I./usr/include -I./ ...
                         -outdir ../bin/mfiles/

mex -v MatlabToXPlane.cpp  ./networking/PCSBSocketUDP.mac.cpp ...
                         -I./networking -I./usr/include -I./ ...
                         -outdir ../bin/mfiles/
end







